basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),

]

gamerMarketCol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls', namespace='basket')),
    path('', include('store.urls', namespace='store')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True,
                            verbose_name=("Category"), help_text="Name of the category")
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        ordering = ['-created']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

basket/views.py
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render

from basket.basket import Basket
from store.models import Product

# Create your views here.


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html',{'basket':basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, product_qty=product_qty)
        basketqty = basket.__len__()
        response =JsonResponse({'product_qty': basketqty})
        return response

store/views.py
from django.shortcuts import get_object_or_404,render
from .models import Category, Product

# Create your views here.

def all_products(request):
    products =Product.products.all()
    return render(request,'store/home.html', {'products': products})

def product_detail(request, slug):
    product= get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request,'store/products/detail.html', {'product': product})


def category_list(request, category_slug):
    category= get_object_or_404(Category, slug=category_slug)
    product = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'products': product})

templates/store/base.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>{%block title%}My Shop{%endblock%}</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
  </script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Products
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories%}
              <li>
                <a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name|title}}</a>
              </li>
              {%endfor %}
            </ul>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
          <button class="btn btn-outline-success" type="submit">
            Search
          </button>
        </form>
        <a type="button" role="button" href="{% url "basket:basket_summary"%}" class="btn-outline-secondary">
          {% with total_qty=basket|length %}
          <div id= "basket-qty" class="d-inline-flex">
          {% if total_qty > 0%}
              {{total_qty}}
            {%else %}
              0
            {% endif %}
            </div>  
          {%endwith%}

          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart2"
            viewBox="0 0 16 16">
            <path
              d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
          </svg>
          Basket
        </a>
      </div>
    </div>
  </nav>
  <div id="content">{%block content%}{%endblock%}</div>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">
        Album example is &copy; Bootstrap, but please download and customize
        it for yourself!
      </p>
      <p class="mb-0">
        New to Bootstrap? <a href="/">Visit the homepage</a> or read our
        <a href="/docs/5.1/getting-started/introduction/">getting started guide</a>.
      </p>
    </div>
  </footer>
</body>

</html>

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping basket</h1>
    {% for item in basket %}
    {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2">{{ product.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">{{product.description }}</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">${{ product.price}}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>
                <select id="select{{product.id}}">
                  <option selected>
                    {{item.product_qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>P
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: $<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div>
      </div>
    </div>
  </div>
</main>


{% endblock %}

templates/store/home.html
{%extends "./base.html"%} {%load static%} {%block title%}Home{%endblock%}
{%block content%}

<main>
  <section class="py-3 text-center container">
    <div class="row py-lg-2">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">
          Something short and leading about the collection below—its contents,
          the creator, etc. Make it short and sweet, but not too short so folks
          don’t simply skip over it entirely.
        </p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-2 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {%for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}" />

            <div class="card-body">
              <p class="card-text">{{product.description}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <form action="{{product.get_absolute_url}}">
                    <input type="submit" value="View {{product.title}}" />
                  </form>
                  <form action="">
                    <input type="submit" value="Shop {{product.title}}" />
                  </form>
                </div>
                <small class="text-muted">{%if product.in_stock %}In Stock{%else %}Out of
                  Stock{%endif%}</small>
              </div>
            </div>
          </div>
        </div>
        {%endfor%}
      </div>
    </div>
  </div>
</main>

{%endblock%}

templates/store/products/category.html
{%extends "../base.html"%} {%load static%} {%block title%}Categories{%endblock%}
{%block content%}

<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {%for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <img
              class="img-fluid"
              alt="Responsive image"
              src="{{product.image.url}}"
            />

            <div class="card-body">
              <p class="card-text">{{product.description}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <form action="{{product.get_absolute_url}}">
                    <input type="submit" value="View {{product.title}}" />
                  </form>
                  <form action="">
                    <input type="submit" value="Shop {{product.title}}" />
                  </form>
                </div>
                <small class="text-muted"
                  >{%if product.in_stock %}In Stock{%else %}Out of
                  Stock{%endif%}</small
                >
              </div>
            </div>
          </div>
        </div>
        {%endfor%}
      </div>
    </div>
  </div>
</main>

{%endblock%}

templates/store/products/detail.html
{% extends "../base.html" %} {% load static %} {% block title %} {{product.title}}
{% endblock %} {% block content %}
<div class="container">
  <main class="pt-5">
    <div class="row g-3">
      <div class="col-md-5 col-lg-5 order-md-first bg-light">
        <img
          class="img-fluid mx-auto d-block"
          width="200px"
          alt="Responsive image"
          src="{{ product.image.url }}"
        />
      </div>
      <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
        <h1 class="mb-0 h4">{{ product.title }}</h1>
        <p><span class="lead">{{ product.title }}</span> (Author)</p>
        <p>{{ product.description|slice:":355" }}...</p>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Hardback</div>
              <div class="col-6 text-end">
                <span class="h4 fw-bold">${{ product.price }}</span>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-6">
                <label for="select">Qty</label>
                <select id="select">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </select>
              </div>
              <div class="col-6 text-end">
                <button
                  type="button"
                  id="add-button"
                  value="{{product.id}}"
                  class="btn btn-secondary btn-sm"
                >
                  Add to basket
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

<script>
  $(document).on("click", "#add-button", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $("#add-button").val(),
        productqty: $("#select option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.product_qty;
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>

{% endblock %}